"""Aggregate editorial metric reports into a reviewable acceptance dossier."""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

from gitbook_worker import __version__
from gitbook_worker.tools.exit_codes import add_exit_code_help, handle_exit_code_help
from gitbook_worker.tools.logging_config import get_logger
from gitbook_worker.tools.quality.editorial_common import (
    EDITORIAL_INVALID_PROFILE_EXIT_CODE,
    EDITORIAL_REPORT_READ_EXIT_CODE,
    AcceptanceProfile,
    exit_code_for_status,
    load_acceptance_profile,
    make_finding,
    severity_counts,
    status_from_counts,
    utc_now_iso,
)

logger = get_logger(__name__)


def build_acceptance_dossier(
    reports: Sequence[Mapping[str, Any]],
    *,
    profile: AcceptanceProfile,
    fail_on_warnings: bool = False,
) -> tuple[str, dict[str, Any]]:
    """Build Markdown dossier text and a structured summary."""

    derived_findings = _derive_report_drift_findings(reports, profile)
    findings = [
        finding for report in reports for finding in report.get("findings", [])
    ] + derived_findings
    counts = severity_counts(findings)
    status = status_from_counts(
        counts, fail_on_warnings=fail_on_warnings or profile.fail_on_warnings
    )
    summary = {
        "schema_version": "1.0.0",
        "generated_at": utc_now_iso(),
        "profile": profile.name,
        "status": status,
        "finding_counts": counts,
        "reports_total": len(reports),
        "findings_total": len(findings),
    }
    lines = [
        "---",
        "version: 1.0.0",
        f"date: {summary['generated_at'][:10]}",
        f"status: {status}",
        "history:",
        '  - "1.0.0: generated by editorial_acceptance"',
        "---",
        "",
        "# Editorial Acceptance Dossier",
        "",
        "## Executive Summary",
        "",
        f"- Profile: `{profile.name}`",
        f"- Status: `{status}`",
        f"- Reports: {len(reports)}",
        f"- Findings: {len(findings)}",
        f"- Blocked: {counts['blocked']}",
        f"- Fail: {counts['fail']}",
        f"- Warn: {counts['warn']}",
        f"- Info: {counts['info']}",
        "",
        "## Inputs",
        "",
    ]
    for report in reports:
        project = report.get("project") or "<unknown>"
        generated_at = report.get("generated_at") or "<unknown>"
        report_status = report.get("summary", {}).get("status", "<unknown>")
        lines.append(
            f"- `{project}` generated `{generated_at}` with status `{report_status}`"
        )

    lines.extend(["", "## PDF Artifacts", ""])
    pdf_artifacts = _collect_pdf_artifacts(reports)
    if not pdf_artifacts:
        lines.append("No PDF artifacts recorded.")
    else:
        for artifact in pdf_artifacts:
            lines.append(
                "- "
                f"`{artifact.get('path', '<pdf>')}`: "
                f"pages={artifact.get('pages_total', 0)}, "
                f"size={artifact.get('file_size_bytes', 0)} bytes, "
                f"created={artifact.get('creation_date') or '<unknown>'}, "
                f"modified={artifact.get('modified_at') or '<unknown>'}"
            )

    lines.extend(["", "## Findings", ""])
    if not findings:
        lines.append("No findings recorded.")
    else:
        grouped = _group_findings(findings)
        for severity in ("blocked", "fail", "warn", "info"):
            if severity not in grouped:
                continue
            lines.extend([f"### {severity}", ""])
            for finding in grouped[severity]:
                lines.extend(_render_finding(finding))

    lines.extend(
        [
            "",
            "## Review Notes",
            "",
            "- Link status is technical reachability, not source truth.",
            "- AI reference checks are search and plausibility aids, not authoritative validation.",
            "- Legal or compliance signals are review prompts, not legal advice.",
            "",
            "## Human Decision",
            "",
            "- Decision: `pending`",
            "- Reviewer role:",
            "- Reviewer name:",
            "- Date:",
            "- Accepted residual risks:",
            "- Notes:",
            "",
        ]
    )
    return "\n".join(lines), summary


def read_metric_reports(paths: Sequence[Path]) -> list[Mapping[str, Any]]:
    """Read JSON metric reports."""

    reports: list[Mapping[str, Any]] = []
    for path in paths:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"Could not read metric report {path}: {exc}") from exc
        if not isinstance(data, Mapping):
            raise ValueError(f"Metric report {path} does not contain a JSON object")
        reports.append(data)
    return reports


def build_arg_parser() -> argparse.ArgumentParser:
    """Build CLI parser for editorial acceptance."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "reports", nargs="*", type=Path, help="Editorial metric JSON reports"
    )
    parser.add_argument(
        "--profile", default="local-preview", help="Editorial profile name"
    )
    parser.add_argument(
        "--profile-config", type=Path, help="YAML file containing editorial profiles"
    )
    parser.add_argument(
        "-o", "--output", type=Path, help="Destination Markdown dossier"
    )
    parser.add_argument(
        "--json-output", type=Path, help="Optional structured acceptance JSON summary"
    )
    parser.add_argument(
        "--fail-on-warnings",
        action="store_true",
        help="Treat warnings as failing acceptance",
    )
    add_exit_code_help(parser)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the editorial acceptance CLI."""

    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        handle_exit_code_help(args, component="editorial")
    except SystemExit as exc:
        return int(exc.code or 0)
    if not args.reports:
        parser.error("at least one editorial metric report is required")
    try:
        profile = load_acceptance_profile(args.profile_config, args.profile)
    except ValueError as exc:
        logger.error("Invalid editorial profile: %s", exc)
        return EDITORIAL_INVALID_PROFILE_EXIT_CODE
    try:
        reports = read_metric_reports(args.reports)
    except ValueError as exc:
        logger.error("%s", exc)
        return EDITORIAL_REPORT_READ_EXIT_CODE

    dossier, summary = build_acceptance_dossier(
        reports, profile=profile, fail_on_warnings=args.fail_on_warnings
    )
    output = args.output or Path("logs") / "quality" / "editorial-acceptance.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dossier, encoding="utf-8")
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(
            json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    logger.info("Editorial acceptance dossier written to %s", output)
    logger.info("Editorial acceptance status=%s", summary["status"])
    return exit_code_for_status(summary["status"])


def _group_findings(
    findings: Sequence[Mapping[str, Any]],
) -> Mapping[str, list[Mapping[str, Any]]]:
    grouped: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for finding in findings:
        grouped[str(finding.get("severity") or "info")].append(finding)
    return grouped


def _render_finding(finding: Mapping[str, Any]) -> list[str]:
    return [
        f"- `{finding.get('id', '<no-id>')}` `{finding.get('rule_id', '<no-rule>')}`",
        f"  - Artifact: `{finding.get('artifact', '')}`",
        f"  - Location: `{finding.get('location', '')}`",
        f"  - Evidence: {finding.get('evidence', '')}",
        f"  - Impact: {finding.get('editorial_impact', '')}",
        f"  - Healing: {finding.get('healing', '')}",
        "",
    ]


def _derive_report_drift_findings(
    reports: Sequence[Mapping[str, Any]], profile: AcceptanceProfile
) -> list[Mapping[str, Any]]:
    findings: list[Mapping[str, Any]] = []
    for report in reports:
        project = str(report.get("project") or "<unknown>")
        generated_at = _parse_iso_datetime(report.get("generated_at"))
        worker_version = str(report.get("worker_version") or "").strip()
        if worker_version and worker_version != __version__:
            severity = (
                "fail" if profile.documentation.fail_on_stale_worker_version else "warn"
            )
            findings.append(
                make_finding(
                    rule_id="report.worker_version.stale",
                    severity=severity,
                    category="report.drift",
                    artifact=project,
                    location="worker_version",
                    evidence=f"report={worker_version}, current={__version__}",
                    editorial_impact="Abnahmereport wurde mit einer anderen Worker-Version erzeugt.",
                    healing="Metriken mit aktueller Worker-Version neu erzeugen oder Abweichung als Restrisiko dokumentieren.",
                ).to_dict()
            )
        elif not worker_version:
            findings.append(
                make_finding(
                    rule_id="report.worker_version.missing",
                    severity="warn",
                    category="report.drift",
                    artifact=project,
                    location="worker_version",
                    evidence="worker_version missing",
                    editorial_impact="Worker-Version des Reports ist nicht nachvollziehbar.",
                    healing="Metrikreport mit aktueller CLI neu erzeugen.",
                ).to_dict()
            )

        if generated_at is None:
            continue
        for pdf_metric in _collect_pdf_artifacts((report,)):
            modified_at = _parse_iso_datetime(pdf_metric.get("modified_at"))
            if modified_at is None or modified_at <= generated_at:
                continue
            severity = (
                "fail" if profile.documentation.fail_on_stale_page_count else "warn"
            )
            findings.append(
                make_finding(
                    rule_id="report.artifact.stale",
                    severity=severity,
                    category="report.drift",
                    artifact=str(pdf_metric.get("path") or project),
                    location="modified_at",
                    evidence=(
                        f"artifact modified {modified_at.isoformat()} after "
                        f"report {generated_at.isoformat()}"
                    ),
                    editorial_impact="Report kann Seitenzahl, Textlayer oder Layout des aktuellen Artefakts verfehlen.",
                    healing="Metrikreport nach dem letzten PDF-Build neu erzeugen.",
                ).to_dict()
            )
    return findings


def _collect_pdf_artifacts(
    reports: Sequence[Mapping[str, Any]],
) -> list[Mapping[str, Any]]:
    artifacts: list[Mapping[str, Any]] = []
    for report in reports:
        metrics = report.get("metrics")
        if not isinstance(metrics, Mapping):
            continue
        pdf_metrics = metrics.get("pdf")
        if not isinstance(pdf_metrics, Sequence) or isinstance(
            pdf_metrics, (str, bytes)
        ):
            continue
        for pdf_metric in pdf_metrics:
            if isinstance(pdf_metric, Mapping):
                artifacts.append(pdf_metric)
    return artifacts


def _parse_iso_datetime(value: Any) -> datetime | None:
    if not value:
        return None
    try:
        text = str(value).replace("Z", "+00:00")
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


if __name__ == "__main__":
    raise SystemExit(main())
